// Do not edit. This file is machine generated by the Resource DLL Wizard.

library pdsm;

{ITE} {DFMFileType} {uImageForm.dfm}
{ITE} {RCFileType} {pdsm_DRC.rc}

{$R 'uImageForm.dfm' ImageForm:TForm}
{$R 'pdsm_DRC.res' 'pdsm_DRC.rc'}

{$E ENU}

begin
end.